# Enable/disable exclusion rules
enable_exclusions: True

# Names for id columns
ids:
  farm: id
  species: id

names:
  species_common_name: common_name
  species_name: name

# Configuration for features
features:
  # Numeric features
  rainfall_mm:
    type: numeric
    short: rainfall
    score_method: num_range #trapezoid
#    tolerance: # for trapezoid scoring
#      left:  100
#      right: 200    
    default_weight: 0.20

  temperature_celsius:
    type: numeric
    short: temperature
    score_method: num_range
    default_weight: 0.20

  elevation_m:
    type: numeric
    short: elevation
    score_method: num_range
    default_weight: 0.20

  ph:
    type: numeric
    short: ph
    score_method: num_range
    default_weight: 0.20

  # Categorical features
  soil_texture:
    type: categorical
    short: soil
    score_method: cat_compatibility
    default_weight: 0.20
    compatibility_pairs:
      sand:
        sand: 1.0
        loamy sand: 0.8
        sandy loam: 0.6
        loam: 0.4
        silty loam: 0.4
        silt: 0.0
        sandy clay loam: 0.4
        clay loam: 0.2
        silty clay loam: 0.2
        sandy clay: 0.0
        silty clay: 0.0
        clay: 0.0
      loamy sand:
        sand: 0.8
        loamy sand: 1.0
        sandy loam: 0.8
        loam: 0.6
        silty loam: 0.6
        silt: 0.4
        sandy clay loam: 0.6
        clay loam: 0.4
        silty clay loam: 0.0
        sandy clay: 0.4
        silty clay: 0.0
        clay: 0.0
      sandy loam:
        sand: 0.6
        loamy sand: 0.8
        sandy loam: 1.0
        loam: 0.8
        silty loam: 0.8
        silt: 0.6
        sandy clay loam: 0.8
        clay loam: 0.6
        silty clay loam: 0.6
        sandy clay: 0.6
        silty clay: 0.4
        clay: 0.4
      loam:
        sand: 0.4
        loamy sand: 0.6
        sandy loam: 0.8
        loam: 1.0
        silty loam: 0.8
        silt: 0.6
        sandy clay loam: 0.8
        clay loam: 0.8
        silty clay loam: 0.6
        sandy clay: 0.6
        silty clay: 0.6
        clay: 0.6
      silty loam:
        sand: 0.4
        loamy sand: 0.6
        sandy loam: 0.8
        loam: 0.8
        silty loam: 1.0
        silt: 0.8
        sandy clay loam: 0.6
        clay loam: 0.8
        silty clay loam: 0.8
        sandy clay: 0.6
        silty clay: 0.6
        clay: 0.6
      silt:
        sand: 0.0
        loamy sand: 0.4
        sandy loam: 0.6
        loam: 0.6
        silty loam: 0.8
        silt: 1.0
        sandy clay loam: 0.4
        clay loam: 0.6
        silty clay loam: 0.6
        sandy clay: 0.4
        silty clay: 0.4
        clay: 0.4
      sandy clay loam:
        sand: 0.4
        loamy sand: 0.6
        sandy loam: 0.8
        loam: 0.8
        silty loam: 0.6
        silt: 0.4
        sandy clay loam: 1.0
        clay loam: 0.8
        silty clay loam: 0.6
        sandy clay: 0.8
        silty clay: 0.6
        clay: 0.6
      clay loam:
        sand: 0.2
        loamy sand: 0.4
        sandy loam: 0.6
        loam: 0.8
        silty loam: 0.8
        silt: 0.6
        sandy clay loam: 0.8
        clay loam: 1.0
        silty clay loam: 0.8
        sandy clay: 0.8
        silty clay: 0.8
        clay: 0.8
      silty clay loam:
        sand: 0.2
        loamy sand: 0.0
        sandy loam: 0.6
        loam: 0.6
        silty loam: 0.8
        silt: 0.6
        sandy clay loam: 0.6
        clay loam: 0.8
        silty clay loam: 1.0
        sandy clay: 0.6
        silty clay: 0.8
        clay: 0.6
      sandy clay:
        sand: 0.0
        loamy sand: 0.4
        sandy loam: 0.6
        loam: 0.6
        silty loam: 0.6
        silt: 0.4
        sandy clay loam: 0.8
        clay loam: 0.8
        silty clay loam: 0.6
        sandy clay: 1.0
        silty clay: 0.6
        clay: 0.8
      silty clay:
        sand: 0.0
        loamy sand: 0.0
        sandy loam: 0.4
        loam: 0.6
        silty loam: 0.6
        silt: 0.4
        sandy clay loam: 0.6
        clay loam: 0.8
        silty clay loam: 0.8
        sandy clay: 0.6
        silty clay: 1.0
        clay: 0.8
      clay:
        sand: 0.0
        loamy sand: 0.0
        sandy loam: 0.4
        loam: 0.6
        silty loam: 0.6
        silt: 0.4
        sandy clay loam: 0.6
        clay loam: 0.8
        silty clay loam: 0.6
        sandy clay: 0.8
        silty clay: 0.8
        clay: 1.0
